<?php
$includes = [
    'admin.form',
    'dao',
    'functions',
];
foreach($includes as $i) {
    module_load_include('inc', 'seinfeld', 'includes/' . $i);
}

/**
 * Implements hook_menu().
 */
function seinfeld_menu() {
    $items['admin/config/system/seinfeld'] = [
        'title' => 'Seinfeld CRM',
        'description' => 'Configure Seinfeld settings and forms.',
        'page callback' => 'drupal_get_form',
        'page arguments' => ['seinfeld_admin_settings'],
        'access arguments' => ['administer seinfeld'],
        'file' => 'includes/admin.form.inc',
    ];
  return $items;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function seinfeld_form_webform_node_form_alter(&$form, $form_state, $form_id) {
    seinfeld_tab_form($form);
}

/**
 *  Webform node submit callback
 */
function seinfeld_submit_handler($form, &$form_state) {
    $values = $form_state['input'];
    $nid = $form_state['complete form']['nid']['#value'];
    SeinfeldDao::put_form($nid, $values);
}

/**
 * Implements hook_form_alter().
 */
function seinfeld_form_alter(&$form, $form_state, $form_id) {
    $sf = get_valid_seinfeld_form($form_id);
    if($sf) {
        $identity = seinfeld_lead_identity_api_call($sf);
        $form['identity'] = [
            '#type' => 'value',
            '#value' => $identity,
        ];
        array_unshift($form['#submit'], 'seinfeld_form_submit');
    }
}

/**
 * Submit callback for Seinfeld enabled forms
 */
function seinfeld_form_submit($form, &$form_state) {
    $form_id = $form['#form_id'];
    $form_values = $form_state['values'];
    $identity = $form_values['identity'];
  
    // Check if it's a Webform.
    $webform = strpos($form_id, 'webform_client_form_');
    if ($webform !== FALSE) {
      $form_values = $form_values['submitted'];
    }
   
    if (!empty($identity)) {
      // Make Lead Convert Api call.
      $lead_id = seinfeld_lead_convert_call($identity, $form_id, $form_values);
    }
  }
  